baseURL = 'https://calebc42.com/'
languageCode = 'en-us'
title = 'Caleb Christensen'
theme = []

[taxonomies]
  tag = "tags"
  category = "categories"

# Render hooks for cleaner HTML
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true # Allows raw HTML if absolutely necessary

  [markup.highlight]
    noClasses = true  # Generates standard classes for syntax highlighting
    style = 'monokai'  # Matches the dark aesthetic of your CSS
    lineNos = false    # We can enable this later if desired
    guessSyntax = false

[params]
  description = "My Knowledge Base"
  author = "Caleb Christensen"

[menu]
  # 1. About
  [[menu.main]]
    identifier = "about"
    name = "[About]"
    url = "/pages/about/"
    weight = 10

  # 2. Contact
    [[menu.main]]
    identifier = "contact"
    name = "[Contact]"
    url = "/pages/contact/" # Ensure you create content/pages/contact.md
    weight = 20

  # 3. Posts (Parent Item)
  # The URL points to the Category Index, serving as the mobile fallback
  [[menu.main]]
    identifier = "posts"
    name = "[Posts]"
    url = "/categories/"
    weight = 30

 # 4. Tags
 [[menu.main]]
   identifier = "tags"
   name = "[Tags]"
   url = "/tags/"
   weight = 40